name: Workflow para deploy no Vercel

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instala o Vercel 
        run: npm install --global vercel@latest

      - name: Configurar Ambiente Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Pull nas informações do Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build do projeto
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy para o Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
